/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResellerRouteRouteImport } from './routes/_authenticated/reseller/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as SCodeIndexRouteImport } from './routes/s.$code.index'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated/reseller/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as SCodeThanksRouteImport } from './routes/s.$code.thanks'
import { Route as SCodeCheckoutRouteImport } from './routes/s.$code.checkout'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as AuthenticatedResellerPayoutsRouteImport } from './routes/_authenticated/reseller/payouts'
import { Route as AuthenticatedResellerOrdersRouteImport } from './routes/_authenticated/reseller/orders'
import { Route as AuthenticatedResellerMarketingRouteImport } from './routes/_authenticated/reseller/marketing'
import { Route as AuthenticatedResellerListingsRouteImport } from './routes/_authenticated/reseller/listings'
import { Route as AuthenticatedResellerDomainRouteImport } from './routes/_authenticated/reseller/domain'
import { Route as AuthenticatedResellerDesignRouteImport } from './routes/_authenticated/reseller/design'
import { Route as AuthenticatedResellerCommissionsRouteImport } from './routes/_authenticated/reseller/commissions'
import { Route as AuthenticatedResellerCatalogRouteImport } from './routes/_authenticated/reseller/catalog'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminResellersRouteImport } from './routes/_authenticated/admin/resellers'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin/marketing'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin/delivery'
import { Route as AuthenticatedAdminCouriersRouteImport } from './routes/_authenticated/admin/couriers'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin/commissions'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin/brands'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as SCodePSlugRouteImport } from './routes/s.$code.p.$slug'
import { Route as ApiPublicSitemapCodeRouteImport } from './routes/api/public/sitemap.$code'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin/products.new'
import { Route as AuthenticatedResellerOrdersIdInvoiceRouteImport } from './routes/_authenticated/reseller/orders.$id.invoice'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResellerRouteRoute =
  AuthenticatedResellerRouteRouteImport.update({
    id: '/reseller',
    path: '/reseller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SCodeIndexRoute = SCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SCodeRoute,
} as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const SCodeThanksRoute = SCodeThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => SCodeRoute,
} as any)
const SCodeCheckoutRoute = SCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SCodeRoute,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellerPayoutsRoute =
  AuthenticatedResellerPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerOrdersRoute =
  AuthenticatedResellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerMarketingRoute =
  AuthenticatedResellerMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerListingsRoute =
  AuthenticatedResellerListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerDomainRoute =
  AuthenticatedResellerDomainRouteImport.update({
    id: '/domain',
    path: '/domain',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerDesignRoute =
  AuthenticatedResellerDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerCommissionsRoute =
  AuthenticatedResellerCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerCatalogRoute =
  AuthenticatedResellerCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResellersRoute =
  AuthenticatedAdminResellersRouteImport.update({
    id: '/resellers',
    path: '/resellers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouriersRoute =
  AuthenticatedAdminCouriersRouteImport.update({
    id: '/couriers',
    path: '/couriers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const SCodePSlugRoute = SCodePSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => SCodeRoute,
} as any)
const ApiPublicSitemapCodeRoute = ApiPublicSitemapCodeRouteImport.update({
  id: '/api/public/sitemap/$code',
  path: '/api/public/sitemap/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedResellerOrdersIdInvoiceRoute =
  AuthenticatedResellerOrdersIdInvoiceRouteImport.update({
    id: '/$id/invoice',
    path: '/$id/invoice',
    getParentRoute: () => AuthenticatedResellerOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/reseller': typeof AuthenticatedResellerRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/s/$code': typeof SCodeRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/couriers': typeof AuthenticatedAdminCouriersRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/reseller/catalog': typeof AuthenticatedResellerCatalogRoute
  '/reseller/commissions': typeof AuthenticatedResellerCommissionsRoute
  '/reseller/design': typeof AuthenticatedResellerDesignRoute
  '/reseller/domain': typeof AuthenticatedResellerDomainRoute
  '/reseller/listings': typeof AuthenticatedResellerListingsRoute
  '/reseller/marketing': typeof AuthenticatedResellerMarketingRoute
  '/reseller/orders': typeof AuthenticatedResellerOrdersRouteWithChildren
  '/reseller/payouts': typeof AuthenticatedResellerPayoutsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/s/$code/checkout': typeof SCodeCheckoutRoute
  '/s/$code/thanks': typeof SCodeThanksRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
  '/s/$code/': typeof SCodeIndexRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/public/sitemap/$code': typeof ApiPublicSitemapCodeRoute
  '/s/$code/p/$slug': typeof SCodePSlugRoute
  '/reseller/orders/$id/invoice': typeof AuthenticatedResellerOrdersIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/couriers': typeof AuthenticatedAdminCouriersRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/reseller/catalog': typeof AuthenticatedResellerCatalogRoute
  '/reseller/commissions': typeof AuthenticatedResellerCommissionsRoute
  '/reseller/design': typeof AuthenticatedResellerDesignRoute
  '/reseller/domain': typeof AuthenticatedResellerDomainRoute
  '/reseller/listings': typeof AuthenticatedResellerListingsRoute
  '/reseller/marketing': typeof AuthenticatedResellerMarketingRoute
  '/reseller/orders': typeof AuthenticatedResellerOrdersRouteWithChildren
  '/reseller/payouts': typeof AuthenticatedResellerPayoutsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/s/$code/checkout': typeof SCodeCheckoutRoute
  '/s/$code/thanks': typeof SCodeThanksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
  '/s/$code': typeof SCodeIndexRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/public/sitemap/$code': typeof ApiPublicSitemapCodeRoute
  '/s/$code/p/$slug': typeof SCodePSlugRoute
  '/reseller/orders/$id/invoice': typeof AuthenticatedResellerOrdersIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/reseller': typeof AuthenticatedResellerRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/s/$code': typeof SCodeRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/couriers': typeof AuthenticatedAdminCouriersRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/resellers': typeof AuthenticatedAdminResellersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/reseller/catalog': typeof AuthenticatedResellerCatalogRoute
  '/_authenticated/reseller/commissions': typeof AuthenticatedResellerCommissionsRoute
  '/_authenticated/reseller/design': typeof AuthenticatedResellerDesignRoute
  '/_authenticated/reseller/domain': typeof AuthenticatedResellerDomainRoute
  '/_authenticated/reseller/listings': typeof AuthenticatedResellerListingsRoute
  '/_authenticated/reseller/marketing': typeof AuthenticatedResellerMarketingRoute
  '/_authenticated/reseller/orders': typeof AuthenticatedResellerOrdersRouteWithChildren
  '/_authenticated/reseller/payouts': typeof AuthenticatedResellerPayoutsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/s/$code/checkout': typeof SCodeCheckoutRoute
  '/s/$code/thanks': typeof SCodeThanksRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
  '/s/$code/': typeof SCodeIndexRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/api/public/sitemap/$code': typeof ApiPublicSitemapCodeRoute
  '/s/$code/p/$slug': typeof SCodePSlugRoute
  '/_authenticated/reseller/orders/$id/invoice': typeof AuthenticatedResellerOrdersIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/reseller'
    | '/dashboard'
    | '/onboarding'
    | '/s/$code'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/couriers'
    | '/admin/delivery'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/reseller/catalog'
    | '/reseller/commissions'
    | '/reseller/design'
    | '/reseller/domain'
    | '/reseller/listings'
    | '/reseller/marketing'
    | '/reseller/orders'
    | '/reseller/payouts'
    | '/api/public/robots'
    | '/s/$code/checkout'
    | '/s/$code/thanks'
    | '/admin/'
    | '/reseller/'
    | '/s/$code/'
    | '/admin/products/new'
    | '/api/public/sitemap/$code'
    | '/s/$code/p/$slug'
    | '/reseller/orders/$id/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/couriers'
    | '/admin/delivery'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/reseller/catalog'
    | '/reseller/commissions'
    | '/reseller/design'
    | '/reseller/domain'
    | '/reseller/listings'
    | '/reseller/marketing'
    | '/reseller/orders'
    | '/reseller/payouts'
    | '/api/public/robots'
    | '/s/$code/checkout'
    | '/s/$code/thanks'
    | '/admin'
    | '/reseller'
    | '/s/$code'
    | '/admin/products/new'
    | '/api/public/sitemap/$code'
    | '/s/$code/p/$slug'
    | '/reseller/orders/$id/invoice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/reseller'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/s/$code'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/couriers'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/resellers'
    | '/_authenticated/admin/settings'
    | '/_authenticated/reseller/catalog'
    | '/_authenticated/reseller/commissions'
    | '/_authenticated/reseller/design'
    | '/_authenticated/reseller/domain'
    | '/_authenticated/reseller/listings'
    | '/_authenticated/reseller/marketing'
    | '/_authenticated/reseller/orders'
    | '/_authenticated/reseller/payouts'
    | '/api/public/robots'
    | '/s/$code/checkout'
    | '/s/$code/thanks'
    | '/_authenticated/admin/'
    | '/_authenticated/reseller/'
    | '/s/$code/'
    | '/_authenticated/admin/products/new'
    | '/api/public/sitemap/$code'
    | '/s/$code/p/$slug'
    | '/_authenticated/reseller/orders/$id/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SCodeRoute: typeof SCodeRouteWithChildren
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapCodeRoute: typeof ApiPublicSitemapCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$code/': {
      id: '/s/$code/'
      path: '/'
      fullPath: '/s/$code/'
      preLoaderRoute: typeof SCodeIndexRouteImport
      parentRoute: typeof SCodeRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/s/$code/thanks': {
      id: '/s/$code/thanks'
      path: '/thanks'
      fullPath: '/s/$code/thanks'
      preLoaderRoute: typeof SCodeThanksRouteImport
      parentRoute: typeof SCodeRoute
    }
    '/s/$code/checkout': {
      id: '/s/$code/checkout'
      path: '/checkout'
      fullPath: '/s/$code/checkout'
      preLoaderRoute: typeof SCodeCheckoutRouteImport
      parentRoute: typeof SCodeRoute
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reseller/payouts': {
      id: '/_authenticated/reseller/payouts'
      path: '/payouts'
      fullPath: '/reseller/payouts'
      preLoaderRoute: typeof AuthenticatedResellerPayoutsRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/orders': {
      id: '/_authenticated/reseller/orders'
      path: '/orders'
      fullPath: '/reseller/orders'
      preLoaderRoute: typeof AuthenticatedResellerOrdersRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/marketing': {
      id: '/_authenticated/reseller/marketing'
      path: '/marketing'
      fullPath: '/reseller/marketing'
      preLoaderRoute: typeof AuthenticatedResellerMarketingRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/listings': {
      id: '/_authenticated/reseller/listings'
      path: '/listings'
      fullPath: '/reseller/listings'
      preLoaderRoute: typeof AuthenticatedResellerListingsRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/domain': {
      id: '/_authenticated/reseller/domain'
      path: '/domain'
      fullPath: '/reseller/domain'
      preLoaderRoute: typeof AuthenticatedResellerDomainRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/design': {
      id: '/_authenticated/reseller/design'
      path: '/design'
      fullPath: '/reseller/design'
      preLoaderRoute: typeof AuthenticatedResellerDesignRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/commissions': {
      id: '/_authenticated/reseller/commissions'
      path: '/commissions'
      fullPath: '/reseller/commissions'
      preLoaderRoute: typeof AuthenticatedResellerCommissionsRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/catalog': {
      id: '/_authenticated/reseller/catalog'
      path: '/catalog'
      fullPath: '/reseller/catalog'
      preLoaderRoute: typeof AuthenticatedResellerCatalogRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resellers': {
      id: '/_authenticated/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AuthenticatedAdminResellersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/couriers': {
      id: '/_authenticated/admin/couriers'
      path: '/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AuthenticatedAdminCouriersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/s/$code/p/$slug': {
      id: '/s/$code/p/$slug'
      path: '/p/$slug'
      fullPath: '/s/$code/p/$slug'
      preLoaderRoute: typeof SCodePSlugRouteImport
      parentRoute: typeof SCodeRoute
    }
    '/api/public/sitemap/$code': {
      id: '/api/public/sitemap/$code'
      path: '/api/public/sitemap/$code'
      fullPath: '/api/public/sitemap/$code'
      preLoaderRoute: typeof ApiPublicSitemapCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/reseller/orders/$id/invoice': {
      id: '/_authenticated/reseller/orders/$id/invoice'
      path: '/$id/invoice'
      fullPath: '/reseller/orders/$id/invoice'
      preLoaderRoute: typeof AuthenticatedResellerOrdersIdInvoiceRouteImport
      parentRoute: typeof AuthenticatedResellerOrdersRoute
    }
  }
}

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminCouriersRoute: typeof AuthenticatedAdminCouriersRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminResellersRoute: typeof AuthenticatedAdminResellersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
    AuthenticatedAdminCouriersRoute: AuthenticatedAdminCouriersRoute,
    AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
    AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminProductsRoute:
      AuthenticatedAdminProductsRouteWithChildren,
    AuthenticatedAdminResellersRoute: AuthenticatedAdminResellersRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedResellerOrdersRouteChildren {
  AuthenticatedResellerOrdersIdInvoiceRoute: typeof AuthenticatedResellerOrdersIdInvoiceRoute
}

const AuthenticatedResellerOrdersRouteChildren: AuthenticatedResellerOrdersRouteChildren =
  {
    AuthenticatedResellerOrdersIdInvoiceRoute:
      AuthenticatedResellerOrdersIdInvoiceRoute,
  }

const AuthenticatedResellerOrdersRouteWithChildren =
  AuthenticatedResellerOrdersRoute._addFileChildren(
    AuthenticatedResellerOrdersRouteChildren,
  )

interface AuthenticatedResellerRouteRouteChildren {
  AuthenticatedResellerCatalogRoute: typeof AuthenticatedResellerCatalogRoute
  AuthenticatedResellerCommissionsRoute: typeof AuthenticatedResellerCommissionsRoute
  AuthenticatedResellerDesignRoute: typeof AuthenticatedResellerDesignRoute
  AuthenticatedResellerDomainRoute: typeof AuthenticatedResellerDomainRoute
  AuthenticatedResellerListingsRoute: typeof AuthenticatedResellerListingsRoute
  AuthenticatedResellerMarketingRoute: typeof AuthenticatedResellerMarketingRoute
  AuthenticatedResellerOrdersRoute: typeof AuthenticatedResellerOrdersRouteWithChildren
  AuthenticatedResellerPayoutsRoute: typeof AuthenticatedResellerPayoutsRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
}

const AuthenticatedResellerRouteRouteChildren: AuthenticatedResellerRouteRouteChildren =
  {
    AuthenticatedResellerCatalogRoute: AuthenticatedResellerCatalogRoute,
    AuthenticatedResellerCommissionsRoute:
      AuthenticatedResellerCommissionsRoute,
    AuthenticatedResellerDesignRoute: AuthenticatedResellerDesignRoute,
    AuthenticatedResellerDomainRoute: AuthenticatedResellerDomainRoute,
    AuthenticatedResellerListingsRoute: AuthenticatedResellerListingsRoute,
    AuthenticatedResellerMarketingRoute: AuthenticatedResellerMarketingRoute,
    AuthenticatedResellerOrdersRoute:
      AuthenticatedResellerOrdersRouteWithChildren,
    AuthenticatedResellerPayoutsRoute: AuthenticatedResellerPayoutsRoute,
    AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
  }

const AuthenticatedResellerRouteRouteWithChildren =
  AuthenticatedResellerRouteRoute._addFileChildren(
    AuthenticatedResellerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedResellerRouteRoute: typeof AuthenticatedResellerRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedResellerRouteRoute: AuthenticatedResellerRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SCodeRouteChildren {
  SCodeCheckoutRoute: typeof SCodeCheckoutRoute
  SCodeThanksRoute: typeof SCodeThanksRoute
  SCodeIndexRoute: typeof SCodeIndexRoute
  SCodePSlugRoute: typeof SCodePSlugRoute
}

const SCodeRouteChildren: SCodeRouteChildren = {
  SCodeCheckoutRoute: SCodeCheckoutRoute,
  SCodeThanksRoute: SCodeThanksRoute,
  SCodeIndexRoute: SCodeIndexRoute,
  SCodePSlugRoute: SCodePSlugRoute,
}

const SCodeRouteWithChildren = SCodeRoute._addFileChildren(SCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SCodeRoute: SCodeRouteWithChildren,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapCodeRoute: ApiPublicSitemapCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
